// Browser tests cover control auth plugin behavior.
import { describe, expect, it } from "vitest";
import type { MarketingClawConfig } from "../../test-support.js";
import { ensureBrowserControlAuth } from "./control-auth.js";

describe("ensureBrowserControlAuth", () => {
  async function expectNoAutoGeneratedAuth(cfg: MarketingClawConfig): Promise<void> {
    const result = await ensureBrowserControlAuth({
      cfg,
      env: { NODE_ENV: "test" },
    });
    expect(result.generatedToken).toBeUndefined();
    expect(result.auth.token).toBeUndefined();
    expect(result.auth.password).toBeUndefined();
  }

  it.each([
    {
      name: "trusted-proxy",
      cfg: {
        gateway: {
          auth: {
            mode: "trusted-proxy",
            trustedProxy: {
              userHeader: "x-forwarded-user",
            },
          },
          trustedProxies: ["192.168.1.1"],
        },
      } satisfies MarketingClawConfig,
    },
    {
      name: "password",
      cfg: {
        gateway: {
          auth: {
            mode: "password",
          },
        },
      } satisfies MarketingClawConfig,
    },
    {
      name: "none",
      cfg: {
        gateway: {
          auth: {
            mode: "none",
          },
        },
      } satisfies MarketingClawConfig,
    },
    {
      name: "token",
      cfg: {
        gateway: {
          auth: {
            mode: "token",
          },
        },
      } satisfies MarketingClawConfig,
    },
  ])("skips auto-generation in test mode for $name mode", async ({ cfg }) => {
    await expectNoAutoGeneratedAuth(cfg);
  });

  describe("token mode", () => {
    it("should return existing token if configured", async () => {
      const cfg: MarketingClawConfig = {
        gateway: {
          auth: {
            mode: "token",
            token: "existing-token-123",
          },
        },
      };

      const result = await ensureBrowserControlAuth({
        cfg,
        env: {} as NodeJS.ProcessEnv,
      });

      expect(result.generatedToken).toBeUndefined();
      expect(result.auth.token).toBe("existing-token-123");
    });
  });
});
