import Foundation

// Stable identifier used for both the macOS LaunchAgent label and Nix-managed defaults suite.
// nix-marketingclaw writes app defaults into this suite to survive app bundle identifier churn.
let launchdLabel = "ai.marketingclaw.mac"
let gatewayLaunchdLabel = "ai.marketingclaw.gateway"
let onboardingVersionKey = "marketingclaw.onboardingVersion"
let onboardingSeenKey = "marketingclaw.onboardingSeen"
let currentOnboardingVersion = 8
let pauseDefaultsKey = "marketingclaw.pauseEnabled"
let iconAnimationsEnabledKey = "marketingclaw.iconAnimationsEnabled"
let swabbleEnabledKey = "marketingclaw.swabbleEnabled"
let swabbleTriggersKey = "marketingclaw.swabbleTriggers"
let voiceWakeTriggerChimeKey = "marketingclaw.voiceWakeTriggerChime"
let voiceWakeSendChimeKey = "marketingclaw.voiceWakeSendChime"
let showDockIconKey = "marketingclaw.showDockIcon"
let defaultVoiceWakeTriggers = ["marketingclaw"]
let voiceWakeMaxWords = 32
let voiceWakeMaxWordLength = 64
let voiceWakeMicKey = "marketingclaw.voiceWakeMicID"
let voiceWakeMicNameKey = "marketingclaw.voiceWakeMicName"
let voiceWakeLocaleKey = "marketingclaw.voiceWakeLocaleID"
let voiceWakeAdditionalLocalesKey = "marketingclaw.voiceWakeAdditionalLocaleIDs"
let voicePushToTalkEnabledKey = "marketingclaw.voicePushToTalkEnabled"
let voiceWakeTriggersTalkModeKey = "marketingclaw.voiceWakeTriggersTalkMode"
let talkEnabledKey = "marketingclaw.talkEnabled"
let talkPhaseSoundsEnabledKey = "marketingclaw.talkPhaseSoundsEnabled"
let talkShiftToStopEnabledKey = "marketingclaw.talkShiftToStopEnabled"
let iconOverrideKey = "marketingclaw.iconOverride"
let connectionModeKey = "marketingclaw.connectionMode"
let remoteTargetKey = "marketingclaw.remoteTarget"
let remoteIdentityKey = "marketingclaw.remoteIdentity"
let remoteProjectRootKey = "marketingclaw.remoteProjectRoot"
let remoteCliPathKey = "marketingclaw.remoteCliPath"
let canvasEnabledKey = "marketingclaw.canvasEnabled"
let cameraEnabledKey = "marketingclaw.cameraEnabled"
let computerControlEnabledKey = "marketingclaw.computerControlEnabled"
let systemRunPolicyKey = "marketingclaw.systemRunPolicy"
let systemRunAllowlistKey = "marketingclaw.systemRunAllowlist"
let systemRunEnabledKey = "marketingclaw.systemRunEnabled"
let locationModeKey = "marketingclaw.locationMode"
let locationPreciseKey = "marketingclaw.locationPreciseEnabled"
let peekabooBridgeEnabledKey = "marketingclaw.peekabooBridgeEnabled"
let deepLinkKeyKey = "marketingclaw.deepLinkKey"
let cliInstallPromptedVersionKey = "marketingclaw.cliInstallPromptedVersion"
let cliValidatedExecutableKey = "marketingclaw.cliValidatedExecutable"
let cliValidatedVersionKey = "marketingclaw.cliValidatedVersion"
let macNodeIdentityProfileKey = "marketingclaw.macNodeIdentityProfile"
let heartbeatsEnabledKey = "marketingclaw.heartbeatsEnabled"
let debugPaneEnabledKey = "marketingclaw.debugPaneEnabled"
let debugFileLogEnabledKey = "marketingclaw.debug.fileLogEnabled"
let appLogLevelKey = "marketingclaw.debug.appLogLevel"
let voiceWakeSupported: Bool = ProcessInfo.processInfo.operatingSystemVersion.majorVersion >= 26
